# Generated by Django 3.2.20 on 2023-10-09 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20230925_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcode',
            options={'permissions': (('can_change_discountcode', 'Can change discount code'),)},
        ),
    ]
